backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "portada"
    label: "Portada del Periódico"
    files:
      - file: "index.html"
        label: "Editar Portada"
        name: "index"
        fields:
          - {label: "Título de la Noticia Destacada", name: "titulo_destacado", widget: "string"}
          - {label: "Texto del Destacado", name: "texto_destacado", widget: "text"}

  - name: "noticias"
    label: "Secciones y Noticias"
    files:
      - file: "noticias.json"
        label: "Lista de Noticias"
        name: "noticias_json"
        fields:
          - label: "Artículos"
            name: "articulos"
            widget: "list"
            fields:
              - {label: "Título de la Noticia", name: "title", widget: "string"}
              - {label: "Sección", name: "seccion", widget: "select", options: ["Ciencia", "Cine y Series", "Deportes", "eSports", "Eventos", "Gaming", "Literatura", "Local", "Mundo Actoral", "Música", "Tecnología"]}
              - {label: "¿Marcar como Destacado?", name: "destacado", widget: "boolean", default: false, required: false}
              - {label: "Fecha de Publicación", name: "date", widget: "datetime"}
              - {label: "Imagen Principal", name: "image", widget: "image", required: false}
              - {label: "Contenido de la Noticia", name: "body", widget: "markdown"}
